### ISSUE TITLE
Parser?

### ISSUE THREAD

**Issue by abritinthebay** [kanaka/miniMAL#1]
Seems like it would be (reasonably) trivial to write a parser for Lisp code (that was Lisp-0 compliant anyhow) by a simple regex.

Someone on Hacker News mentioned this for python:

`def parse(s): return json.loads('['+re.sub('([")])\s*(["(])','\g<1>,\g<2>',re.sub('[^()\s]+','"\g<0>"',s)).replace('(','[').replace(')',']')+']')``

Seems like most of that should go 1-to-1 into a JSON regex (as naive as it is). 

Just a thought....

**Comment by kanaka** [comment]
@abritinthebay yep, you certainly could. You would need to handle strings properly (including escaped quotes and parens within strings, etc), but you could definitely have a translator.

Unfortunately, regex doesn't tend to compress well (it's already rather concise), so I wouldn't include it in the main code base for which minimal size is one of the key motivators. Also, JSON as the primary source is, IMO, a unique and interesting aspect of miniMAL. That being said, if somebody sent me a pull request with a utility program to translate back and forth, I would probably merge it.

**Comment by abritinthebay** [comment]
All good points. The only reason I'd suggest a simple parser (even if it was a function in the docs) is to allow Lisp people to quickly test miniMAL.

Maybe not even in the core lib, just in the readme ;)

I'm curious - have you played around with any benchmarks of miniMAL vs vanilla JS? I'd be curious to see what the overhead was (minimal I'd imagine).

**Comment by kanaka** [comment]
@abritinthebay I look forward to the pull request with the parser/translator ;-)

Unfortunately, performance is nowhere near as fast as native JS. The reason is because miniMAL is an interpreter and is not generating/compiling to JS (unlike something like ClojureScript). So even if ["+", 2, 3] happens multiple times in the code, there is a lot of miniMAL code that runs to perform the operation every time.

**Comment by Myhlamaeus** [comment]
See [ileri/lisp-to-array](/ileri/lisp-to-array) for an implementation via JISON.
