### ISSUE TITLE
Modulus?

### ISSUE THREAD

**Issue by whitelizard** [kanaka/miniMAL#36]
Is there a good reason why modulus ("%") is not among the available operators?

Should it be, or is there an easy way around it?

**Comment by whitelizard** [comment]
Never mind!

```js
mLisp['%'] = (...a) => a[0] % a[1];
```

**Comment by kanaka** [comment]
Yeah, =, <, +, -, *, and / are pre-defined for convenience. I almost left them out to get the implementation even smaller, but they are useful examples for the early implementation steps and I was able to keep them and still be below the 1024 byte budget :-)
